### ISSUE TITLE
Problem with concurrently --kill-others "npm run hot-server" "npm run start-hot"

### ISSUE THREAD

**Issue by taniadaniela** [web-pal/DBGlass#33]
Hello there, I'm trying to build the app from source but I'm having this issue when running 
```
npm run dev
Problem with concurrently --kill-others "npm run hot-server" "npm run start-hot"
```

Here is the info at npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@4.0.2
3 info using node@v6.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle DBGlass@0.0.0~predev: DBGlass@0.0.0
6 silly lifecycle DBGlass@0.0.0~predev: no script for predev, continuing
7 info lifecycle DBGlass@0.0.0~dev: DBGlass@0.0.0
8 verbose lifecycle DBGlass@0.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle DBGlass@0.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/taniadaniela/DBGlass/node_modules/.bin:/Users/taniadaniela/.rvm/gems/ruby-2.3.0/bin:/Users/taniadaniela/.rvm/gems/ruby-2.3.0@global/bin:/Users/taniadaniela/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/taniadaniela/.rvm/bin:/Users/taniadaniela/.rvm/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/sbin:/usr/local/git/bin:/usr/local/bin
10 verbose lifecycle DBGlass@0.0.0~dev: CWD: /Users/taniadaniela/DBGlass
11 silly lifecycle DBGlass@0.0.0~dev: Args: [ '-c',
11 silly lifecycle   'concurrently --kill-others "npm run hot-server" "npm run start-hot"' ]
12 info lifecycle DBGlass@0.0.0~dev: Failed to exec dev script
13 verbose stack Error: DBGlass@0.0.0 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid DBGlass@0.0.0
15 verbose cwd /Users/taniadaniela/DBGlass
16 error Darwin 15.6.0
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 error node v6.9.1
19 error npm  v4.0.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error DBGlass@0.0.0 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
24 error spawn ENOENT
25 error Failed at the DBGlass@0.0.0 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the DBGlass package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     concurrently --kill-others "npm run hot-server" "npm run start-hot"
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs DBGlass
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls DBGlass
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

Any ideas? thanks..

**Comment by ilya-lopukhin** [comment]
Do you have `concurrently` installed? Does it fail with other commands? Try installing concurrently globally with `npm i -g concurrently` and test it with `concurrently "echo '1'" "echo '2'"`

**Comment by taniadaniela** [comment]
fixed, I did ```npm i -g concurrently && npm install cross-env``` and it worked.. 

Thanks @Architektor
